[2024-09-02T16:28:41.764+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-02T16:28:41.776+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag_v3.task3 manual__2024-09-02T16:28:39.967234+00:00 [queued]>
[2024-09-02T16:28:41.781+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag_v3.task3 manual__2024-09-02T16:28:39.967234+00:00 [queued]>
[2024-09-02T16:28:41.783+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 6
[2024-09-02T16:28:41.792+0000] {taskinstance.py:2879} INFO - Executing <Task(BashOperator): task3> on 2024-09-02 16:28:39.967234+00:00
[2024-09-02T16:28:41.799+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=4277) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-02T16:28:41.801+0000] {standard_task_runner.py:72} INFO - Started process 4279 to run task
[2024-09-02T16:28:41.799+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v3', 'task3', 'manual__2024-09-02T16:28:39.967234+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmpwpg5pauf']
[2024-09-02T16:28:41.802+0000] {standard_task_runner.py:105} INFO - Job 14: Subtask task3
[2024-09-02T16:28:41.852+0000] {task_command.py:467} INFO - Running <TaskInstance: our_first_dag_v3.task3 manual__2024-09-02T16:28:39.967234+00:00 [running]> on host cedbab6b7256
[2024-09-02T16:28:41.902+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='abhay' AIRFLOW_CTX_DAG_ID='our_first_dag_v3' AIRFLOW_CTX_TASK_ID='task3' AIRFLOW_CTX_EXECUTION_DATE='2024-09-02T16:28:39.967234+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-02T16:28:39.967234+00:00'
[2024-09-02T16:28:41.903+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-02T16:28:41.916+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-09-02T16:28:41.918+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo Yo I am task3']
[2024-09-02T16:28:41.926+0000] {subprocess.py:86} INFO - Output:
[2024-09-02T16:28:41.928+0000] {subprocess.py:93} INFO - Yo I am task3
[2024-09-02T16:28:41.929+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-09-02T16:28:41.946+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-02T16:28:41.947+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v3, task_id=task3, run_id=manual__2024-09-02T16:28:39.967234+00:00, execution_date=20240902T162839, start_date=20240902T162841, end_date=20240902T162841
[2024-09-02T16:28:41.976+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2024-09-02T16:28:41.999+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-02T16:28:42.001+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
