[2024-09-08T00:00:02.791+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-08T00:00:02.817+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_first_dag_v3.third_task scheduled__2024-09-07T00:00:00+00:00 [queued]>
[2024-09-08T00:00:02.829+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_first_dag_v3.third_task scheduled__2024-09-07T00:00:00+00:00 [queued]>
[2024-09-08T00:00:02.831+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 6
[2024-09-08T00:00:02.871+0000] {taskinstance.py:2879} INFO - Executing <Task(BashOperator): third_task> on 2024-09-07 00:00:00+00:00
[2024-09-08T00:00:02.926+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=61748) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-08T00:00:02.941+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'my_first_dag_v3', 'third_task', 'scheduled__2024-09-07T00:00:00+00:00', '--job-id', '213', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmpta6h0k6y']
[2024-09-08T00:00:02.944+0000] {standard_task_runner.py:72} INFO - Started process 61750 to run task
[2024-09-08T00:00:02.948+0000] {standard_task_runner.py:105} INFO - Job 213: Subtask third_task
[2024-09-08T00:00:03.059+0000] {task_command.py:467} INFO - Running <TaskInstance: my_first_dag_v3.third_task scheduled__2024-09-07T00:00:00+00:00 [running]> on host 626f2e28dec2
[2024-09-08T00:00:03.163+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='abhay' AIRFLOW_CTX_DAG_ID='my_first_dag_v3' AIRFLOW_CTX_TASK_ID='third_task' AIRFLOW_CTX_EXECUTION_DATE='2024-09-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-07T00:00:00+00:00'
[2024-09-08T00:00:03.165+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-08T00:00:03.182+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-09-08T00:00:03.184+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo Yo I am task3']
[2024-09-08T00:00:03.199+0000] {subprocess.py:86} INFO - Output:
[2024-09-08T00:00:03.203+0000] {subprocess.py:93} INFO - Yo I am task3
[2024-09-08T00:00:03.209+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-09-08T00:00:03.241+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-08T00:00:03.242+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=my_first_dag_v3, task_id=third_task, run_id=scheduled__2024-09-07T00:00:00+00:00, execution_date=20240907T000000, start_date=20240908T000002, end_date=20240908T000003
[2024-09-08T00:00:03.294+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2024-09-08T00:00:03.312+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
