[2024-09-04T18:18:18.085+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-04T18:18:18.110+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_first_dag_v3.first_task manual__2024-09-04T18:18:17.337128+00:00 [queued]>
[2024-09-04T18:18:18.117+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_first_dag_v3.first_task manual__2024-09-04T18:18:17.337128+00:00 [queued]>
[2024-09-04T18:18:18.119+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 6
[2024-09-04T18:18:18.129+0000] {taskinstance.py:2879} INFO - Executing <Task(BashOperator): first_task> on 2024-09-04 18:18:17.337128+00:00
[2024-09-04T18:18:18.137+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=343) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-04T18:18:18.141+0000] {standard_task_runner.py:72} INFO - Started process 344 to run task
[2024-09-04T18:18:18.138+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'my_first_dag_v3', 'first_task', 'manual__2024-09-04T18:18:17.337128+00:00', '--job-id', '100', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmplrfdpcgq']
[2024-09-04T18:18:18.143+0000] {standard_task_runner.py:105} INFO - Job 100: Subtask first_task
[2024-09-04T18:18:18.185+0000] {task_command.py:467} INFO - Running <TaskInstance: my_first_dag_v3.first_task manual__2024-09-04T18:18:17.337128+00:00 [running]> on host f1e60abe9381
[2024-09-04T18:18:18.263+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='abhay' AIRFLOW_CTX_DAG_ID='my_first_dag_v3' AIRFLOW_CTX_TASK_ID='first_task' AIRFLOW_CTX_EXECUTION_DATE='2024-09-04T18:18:17.337128+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-04T18:18:17.337128+00:00'
[2024-09-04T18:18:18.264+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-04T18:18:18.279+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-09-04T18:18:18.281+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo hello world, this is the first task!']
[2024-09-04T18:18:18.298+0000] {subprocess.py:86} INFO - Output:
[2024-09-04T18:18:18.301+0000] {subprocess.py:93} INFO - hello world, this is the first task!
[2024-09-04T18:18:18.311+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-09-04T18:18:18.334+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-04T18:18:18.335+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=my_first_dag_v3, task_id=first_task, run_id=manual__2024-09-04T18:18:17.337128+00:00, execution_date=20240904T181817, start_date=20240904T181818, end_date=20240904T181818
[2024-09-04T18:18:18.358+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2024-09-04T18:18:18.372+0000] {taskinstance.py:3891} INFO - 2 downstream tasks scheduled from follow-on schedule check
[2024-09-04T18:18:18.375+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
