[2024-09-02T01:41:18.166+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-02T01:41:18.177+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: example_python_operator.external_python manual__2024-09-02T01:41:15.472675+00:00 [queued]>
[2024-09-02T01:41:18.183+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: example_python_operator.external_python manual__2024-09-02T01:41:15.472675+00:00 [queued]>
[2024-09-02T01:41:18.184+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 1
[2024-09-02T01:41:18.191+0000] {taskinstance.py:2879} INFO - Executing <Task(ExternalPythonOperator): external_python> on 2024-09-02 01:41:15.472675+00:00
[2024-09-02T01:41:18.199+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1311) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-02T01:41:18.199+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'example_python_operator', 'external_python', 'manual__2024-09-02T01:41:15.472675+00:00', '--job-id', '4', '--raw', '--subdir', '/home/***/.local/lib/python3.12/site-packages/***/example_dags/example_python_operator.py', '--cfg-path', '/tmp/tmpwz6g0yvo']
[2024-09-02T01:41:18.200+0000] {standard_task_runner.py:72} INFO - Started process 1313 to run task
[2024-09-02T01:41:18.201+0000] {standard_task_runner.py:105} INFO - Job 4: Subtask external_python
[2024-09-02T01:41:18.265+0000] {task_command.py:467} INFO - Running <TaskInstance: example_python_operator.external_python manual__2024-09-02T01:41:15.472675+00:00 [running]> on host 453e90e1ba4d
[2024-09-02T01:41:18.326+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='example_python_operator' AIRFLOW_CTX_TASK_ID='external_python' AIRFLOW_CTX_EXECUTION_DATE='2024-09-02T01:41:15.472675+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-02T01:41:15.472675+00:00'
[2024-09-02T01:41:18.329+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-09-02T01:41:18.330+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-09-02T01:41:18.332+0000] {logging_mixin.py:190} INFO - Current task name:external_python state:running start_date:2024-09-02 01:41:18.178948+00:00
[2024-09-02T01:41:18.333+0000] {logging_mixin.py:190} INFO - Dag name:example_python_operator and current dag run status:running
[2024-09-02T01:41:18.334+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-02T01:41:18.603+0000] {baseoperator.py:405} WARNING - ExternalPythonOperator.execute cannot be called outside TaskInstance!
[2024-09-02T01:41:18.632+0000] {process_utils.py:186} INFO - Executing cmd: /home/***/.local/bin/python /tmp/venv-callnji2cex5/script.py /tmp/venv-callnji2cex5/script.in /tmp/venv-callnji2cex5/script.out /tmp/venv-callnji2cex5/string_args.txt /tmp/venv-callnji2cex5/termination.log
[2024-09-02T01:41:18.634+0000] {process_utils.py:190} INFO - Output:
[2024-09-02T01:41:21.572+0000] {process_utils.py:194} INFO - /home/***/.local/lib/python3.12/site-packages/***/plugins_manager.py:30 DeprecationWarning: 'cgitb' is deprecated and slated for removal in Python 3.13
[2024-09-02T01:41:22.706+0000] {process_utils.py:194} INFO - Running task via /home/***/.local/bin/python
[2024-09-02T01:41:22.713+0000] {process_utils.py:194} INFO - Sleeping
[2024-09-02T01:41:22.715+0000] {process_utils.py:194} INFO - Please wait...
[2024-09-02T01:41:23.708+0000] {process_utils.py:194} INFO - Please wait...
[2024-09-02T01:41:24.708+0000] {process_utils.py:194} INFO - Please wait...
[2024-09-02T01:41:25.708+0000] {process_utils.py:194} INFO - Please wait...
[2024-09-02T01:41:26.769+0000] {process_utils.py:194} INFO - Finished
[2024-09-02T01:41:27.536+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-09-02T01:41:27.555+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-02T01:41:27.558+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=example_python_operator, task_id=external_python, run_id=manual__2024-09-02T01:41:15.472675+00:00, execution_date=20240902T014115, start_date=20240902T014118, end_date=20240902T014127
[2024-09-02T01:41:27.568+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2024-09-02T01:41:27.570+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-09-02T01:41:27.571+0000] {logging_mixin.py:190} INFO - Dag name:example_python_operator queued_at:2024-09-02 01:41:15.600936+00:00
[2024-09-02T01:41:27.572+0000] {logging_mixin.py:190} INFO - Task hostname:453e90e1ba4d operator:ExternalPythonOperator
[2024-09-02T01:41:27.624+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2024-09-02T01:41:27.668+0000] {taskinstance.py:3891} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-09-02T01:41:27.672+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
