[2024-09-04T18:22:02.398+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-04T18:22:02.412+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_first_dag_v3.second_task manual__2024-09-04T18:22:00.450616+00:00 [queued]>
[2024-09-04T18:22:02.418+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_first_dag_v3.second_task manual__2024-09-04T18:22:00.450616+00:00 [queued]>
[2024-09-04T18:22:02.419+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 6
[2024-09-04T18:22:02.432+0000] {taskinstance.py:2879} INFO - Executing <Task(BashOperator): second_task> on 2024-09-04 18:22:00.450616+00:00
[2024-09-04T18:22:02.452+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=506) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-04T18:22:02.459+0000] {standard_task_runner.py:72} INFO - Started process 509 to run task
[2024-09-04T18:22:02.460+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'my_first_dag_v3', 'second_task', 'manual__2024-09-04T18:22:00.450616+00:00', '--job-id', '105', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmpxqh3gw4s']
[2024-09-04T18:22:02.467+0000] {standard_task_runner.py:105} INFO - Job 105: Subtask second_task
[2024-09-04T18:22:02.541+0000] {task_command.py:467} INFO - Running <TaskInstance: my_first_dag_v3.second_task manual__2024-09-04T18:22:00.450616+00:00 [running]> on host f1e60abe9381
[2024-09-04T18:22:02.700+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='abhay' AIRFLOW_CTX_DAG_ID='my_first_dag_v3' AIRFLOW_CTX_TASK_ID='second_task' AIRFLOW_CTX_EXECUTION_DATE='2024-09-04T18:22:00.450616+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-04T18:22:00.450616+00:00'
[2024-09-04T18:22:02.708+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-04T18:22:02.744+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-09-04T18:22:02.748+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo I am the second task!']
[2024-09-04T18:22:02.762+0000] {subprocess.py:86} INFO - Output:
[2024-09-04T18:22:02.766+0000] {subprocess.py:93} INFO - I am the second task!
[2024-09-04T18:22:02.768+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-09-04T18:22:02.821+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-04T18:22:02.824+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=my_first_dag_v3, task_id=second_task, run_id=manual__2024-09-04T18:22:00.450616+00:00, execution_date=20240904T182200, start_date=20240904T182202, end_date=20240904T182202
[2024-09-04T18:22:02.893+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2024-09-04T18:22:02.932+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
